packages:
  - 'apps/**/*'
  - 'packages/**/*'
overrides:
  '@types/node': '^22.15.18'
  'typescript': '^5.8.3'
  'esbuild': '^0.25.3'
  'tsc-alias': '^1.8.16'
  'vite': '^6.3.4'
  '@vitejs/plugin-react-swc': '^3.9.0'
  '@vitejs/plugin-react': '^4.4.1'
  '@vitest/coverage-v8': '^3.1.2'
  'vite-bundle-visualizer': '^1.2.1'
  'vite-plugin-image-optimizer': '^1.1.8'
  'vite-plugin-node-polyfills': '^0.23.0'
  'vite-tsconfig-paths': '^5.1.4'
  'vitest': '^3.1.2'
  '@types/react': '^19.0.0'
  '@types/react-dom': '^19.1.3'
  'react': '^19.0.0'
  'react-dom': '^19.0.0'
  'react-router': '^7.5.3'
