export const TILE_MOVE_ANIMATION_DURATION = 150;
export const TILE_CREATION_ANIMATION_DURATION = 400;
export const TILE_POP_ANIMATION_DURATION = 400;

export const TILE_Z_INDEX = 2;
export const EMPTY_TILE_Z_INDEX = 0;
export const MOVING_TILE_Z_INDEX = 1;
