import {PAGE_ID} from './PAGE_ID';

export const PAGE_ID_TO_NAME = {
    [PAGE_ID.LOGIN]: '登录',

    [PAGE_ID.MANAGE.INDEX]: '网站管理',

    [PAGE_ID.MANAGE.BLOG.ARTICLE.ADD]: '文章添加',
    [PAGE_ID.MANAGE.BLOG.ARTICLE.MANAGE]: '文章管理',
    [PAGE_ID.MANAGE.BLOG.ARTICLE.MODIFY]: '文章修改',

    [PAGE_ID.MANAGE.BLOG.CATEGORY.ADD]: '文章分类添加',
    [PAGE_ID.MANAGE.BLOG.CATEGORY.MANAGE]: '文章分类管理',

    [PAGE_ID.MANAGE.BLOG.OPTION.ABOUT]: '关于我设置',
};
