worker_processes auto;

error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  log_format main
    '[$server_name] $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
  access_log /dev/stdout main;

  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;

  http2 on;
  http3 on;

  client_max_body_size 10m;

  # Rate limiting
  limit_req_zone $binary_remote_addr zone=global:10m rate=10r/s;
  limit_req zone=global burst=30 nodelay;
  limit_req_status 429;

  keepalive_timeout 65;

  gzip on;
  gzip_vary on;
  gzip_comp_level 5;
  gzip_proxied any;
  gzip_types text/css
    text/plain
    text/xml
    text/javascript
    text/mathml
    application/json
    application/javascript
    application/xml
    application/rss+xml
    application/atom+xml
    application/xhtml+xml
    application/manifest+json
    application/wasm
    image/svg+xml
    image/x-ms-bmp
    font/woff;

  include /etc/nginx/security.conf;
  include /etc/nginx/conf.d/*.conf;
}

include /etc/nginx/tcp.d/*.conf;