name: admin-build

on:
    push:
        branches:
            - 'main'
        paths:
            - 'apps/admin/**'
            - 'Dockerfile'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  target: 'admin'
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/admin:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
