name: CI Build Admin Docker Image

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/admin-vite/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      docker-file-path: ./Dockerfile
      docker-build-target: admin
      push: false
