name: Build and Push Admin Docker Image

on:
    push:
        branches:
            - 'main'
        paths:
            - 'apps/admin/**'
            - 'packages/**'
            - 'pnpm-lock.yaml'
            - 'Dockerfile'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: ./.github/workflows/docker-build.yml
              with: 
                docker-build-target: admin
