name: Build and Push Blog Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/blog/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/docker-build-and-push.yml
    secrets: inherit
    with:
      docker-file-path: ./Dockerfile
      docker-build-target: blog
      push: true
