name: blog-build

on:
    push:
        branches:
            - 'main'
        paths:
            - 'apps/blog/**'
            - 'packages/**'
            - 'pnpm-lock.yaml'
            - 'Dockerfile'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/docker-build.yml
              with:
                  docker-build-target: blog
