name: Build and Push Blog Docker Image

on:
    push:
        branches:
            - 'main'
        paths:
            - 'apps/blog/**'
            - 'packages/**'
            - 'pnpm-lock.yaml'
            - 'Dockerfile'
    workflow_dispatch:

jobs:
    build:
        uses: ./.github/workflows/docker-build.yml
        secrets: inherit
        with:
            docker-file-path: ./Dockerfile
            docker-build-target: blog
