name: CI Build Blog Docker Image

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/blog/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: docker-build-and-push.yml
    secrets: inherit
    with:
      docker-file-path: ./Dockerfile
      docker-build-target: blog
      push: false
