name: Nginx CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'nginx/configurations/**'
      - 'nginx/Dockerfile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/docker-image-build-and-push.yml
    secrets: inherit
    with:
      docker-file-path: ./nginx/Dockerfile
      docker-build-target: website-nginx
      push-to-registry: false
