name: Build and Push NGINX Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'nginx/configurations/**'
      - 'nginx/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      docker-file-path: ./nginx/Dockerfile
      docker-build-target: website-nginx
